### ISSUE TITLE
cmake 3.15: issue with find_package(python ...)

### ISSUE THREAD

**Issue by looooo** [conda-forge/cmake-feedstock#91]
There is a problem with `find_package(python ...)`. For python3.6 host-environment the more recent python3.7 of the base-environment is found. issue encountered with py36 osx/linux

ref.: https://github.com/conda-forge/staged-recipes/pull/8474

**Comment by isuruf** [comment]
Please be more specific with the details when opening an issue

**Comment by looooo** [comment]
Sorry I do not have much more information. Maybe the output of the linked project helps to understand the issue:

command:
https://github.com/aewallin/opencamlib/blob/master/src/pythonlib/pythonlib.cmake#L64
`find_package(Python3 COMPONENTS Interpreter Development)`

output for py36:
```
Found Python3: /opt/conda/bin/python3.7 (found version "3.7.3") found components:  Interpreter Development
```

which is obviously wrong for a conda-recipe.

**Comment by marcelotrevisani** [comment]
From my point of view, this problem is related to ``cmake`` rather the recipe itself.
I think when you invoke cmake you should specify the ``lib`` folders of your environment, I have found some problems with ``cmake`` and virtual envs. That might be another one.

**Comment by tadeu** [comment]
This is possibly related to a change on `FindPython` for CMake 3.15, check the `Python_FIND_STRATEGY`:

https://cmake.org/cmake/help/v3.15/module/FindPython.html#hints

and this policy:

https://cmake.org/cmake/help/v3.15/policy/CMP0094.html#policy:CMP0094

When using CMake with `conda`, either this policy should be set with `Old` or `Python_FIND_STRATEGY` should be set to `LOCATION` explicitly, otherwise, if there's a newer version in the system, CMake will use that version :(. Note that, on Windows, a change in `Python_FIND_REGISTRY` will also make it prioritize a Python installed in the system (rather that the one from `conda`).

I agree that it's more a an issue with `cmake` itself rather than this package, but this will start to affect a lot of recipes that rely on CMake finding the correct Python.

An idea: do you think that this package could configure the policy to "Old" by default, or would it be too intrusive?

**Comment by tadeu** [comment]
@looooo, could you please try your recipe with CMake 3.15 and passing `-D Python3_FIND_STRATEGY=LOCATION`?

**Comment by looooo** [comment]
@tadeu thanks for the information.
https://github.com/conda-forge/opencamlib-feedstock/pull/1

**Comment by tadeu** [comment]
Relevant issue in CMake bug tracking system: https://gitlab.kitware.com/cmake/cmake/issues/19159

**Comment by looooo** [comment]
Setting `Python3_FIND_STRATEGY=LOCATION` did the trick. So I guess this issue can be closed.
